-- ============================================================================
-- SmartMeters Connector v3.0 - Database Schema
-- Oracle 19c Compatible
-- ============================================================================
-- This schema supports:
--   - Multi-source: ZFA, ITRON
--   - Multi-type: MEASURE, ALARM, EVENT
--   - Horizontal pivot Q1-Q100 for interval data
--   - SECTION_UUID tracking per channel
--   - Artemis direct consumption (no SAP integration)
-- ============================================================================

-- ============================================================================
-- MASTER/HEADER TABLE: SMC_MDM_SCCURVES_HD
-- ============================================================================
-- Stores message-level metadata for each incoming push
-- ============================================================================

CREATE TABLE SMC_MDM_SCCURVES_HD (
    LOG_ID              NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SOURCE_SYSTEM       VARCHAR2(20) NOT NULL,      -- 'ZFA' or 'ITRON'
    SOURCE_TYPE         VARCHAR2(20) NOT NULL,      -- 'MEASURE', 'ALARM', 'EVENT'
    FILE_ID             VARCHAR2(100),              -- ITRON file ID
    FILE_NAME           VARCHAR2(500),              -- ITRON file name
    MESSAGE_UUID        VARCHAR2(100),              -- Unique message identifier
    WSDL_OPERATION      VARCHAR2(100),              -- WSDL operation name
    ENDPOINT            VARCHAR2(500),              -- Receiving endpoint URL
    SENDER_ID           VARCHAR2(100),              -- Sender party ID
    RECIPIENT_ID        VARCHAR2(100),              -- Recipient party ID
    SOURCE_CREATION_DT  TIMESTAMP,                  -- Message creation timestamp
    STATUS              VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    STATUS_MSG          VARCHAR2(4000),             -- Error message if failed
    RECORDS_PROCESSED   NUMBER(10) DEFAULT 0,       -- Count of curve records created
    RAW_XML             CLOB,                       -- Original XML payload for audit
    RECEIVED_AT         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    DT_UPDATE           TIMESTAMP,
    CONSTRAINT CHK_HD_SOURCE_SYSTEM CHECK (SOURCE_SYSTEM IN ('ZFA', 'ITRON')),
    CONSTRAINT CHK_HD_SOURCE_TYPE CHECK (SOURCE_TYPE IN ('MEASURE', 'ALARM', 'EVENT')),
    CONSTRAINT CHK_HD_STATUS CHECK (STATUS IN ('PENDING', 'PROCESSING', 'SUCCESS', 'ERROR', 'PARTIAL'))
);

-- Indexes for SMC_MDM_SCCURVES_HD
CREATE INDEX IDX_HD_STATUS ON SMC_MDM_SCCURVES_HD(STATUS);
CREATE INDEX IDX_HD_MESSAGE_UUID ON SMC_MDM_SCCURVES_HD(MESSAGE_UUID);
CREATE INDEX IDX_HD_SOURCE_SYSTEM ON SMC_MDM_SCCURVES_HD(SOURCE_SYSTEM, SOURCE_TYPE);
CREATE INDEX IDX_HD_RECEIVED_AT ON SMC_MDM_SCCURVES_HD(RECEIVED_AT);
CREATE INDEX IDX_HD_SENDER_ID ON SMC_MDM_SCCURVES_HD(SENDER_ID);

COMMENT ON TABLE SMC_MDM_SCCURVES_HD IS 'Master table for MDM curve data imports - header level';
COMMENT ON COLUMN SMC_MDM_SCCURVES_HD.LOG_ID IS 'Auto-generated primary key';
COMMENT ON COLUMN SMC_MDM_SCCURVES_HD.SOURCE_SYSTEM IS 'Source system identifier (ZFA or ITRON)';
COMMENT ON COLUMN SMC_MDM_SCCURVES_HD.SOURCE_TYPE IS 'Data type (MEASURE, ALARM, EVENT)';
COMMENT ON COLUMN SMC_MDM_SCCURVES_HD.RAW_XML IS 'Original XML payload stored for audit and replay';

-- ============================================================================
-- CURVE DATA TABLE: SMC_MDM_SCCURVES
-- ============================================================================
-- Stores processed curve data with horizontal pivot (Q1-Q100, S1-S100)
-- One row per POD + Channel + Date
-- ============================================================================

CREATE TABLE SMC_MDM_SCCURVES (
    CURVE_ID            NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    HD_LOG_ID           NUMBER(19) NOT NULL,        -- FK to SMC_MDM_SCCURVES_HD
    SECTION_UUID        VARCHAR2(100),              -- Section/Channel UUID from XML
    POD_ID              VARCHAR2(22) NOT NULL,      -- Point of Delivery (full 22 chars)
    SUPPLY_NUM          VARCHAR2(9),                -- Supply number (extracted from POD)
    DATE_READ           DATE NOT NULL,              -- Greek local date
    DATA_CLASS          VARCHAR2(50),               -- OBIS code / Measurement type
    UNIT_MEASURE        VARCHAR2(10),               -- Unit (KWH, KVARH, etc.)
    SOURCE_SYSTEM       VARCHAR2(20),               -- 'ZFA' or 'ITRON'
    SOURCE_CREATION_DT  TIMESTAMP,                  -- Original creation timestamp
    DT_CREATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    -- Q1-Q100: Quantity values for 15-min intervals (96 normal + 4 for DST)
    Q1 NUMBER(15,4), Q2 NUMBER(15,4), Q3 NUMBER(15,4), Q4 NUMBER(15,4), Q5 NUMBER(15,4),
    Q6 NUMBER(15,4), Q7 NUMBER(15,4), Q8 NUMBER(15,4), Q9 NUMBER(15,4), Q10 NUMBER(15,4),
    Q11 NUMBER(15,4), Q12 NUMBER(15,4), Q13 NUMBER(15,4), Q14 NUMBER(15,4), Q15 NUMBER(15,4),
    Q16 NUMBER(15,4), Q17 NUMBER(15,4), Q18 NUMBER(15,4), Q19 NUMBER(15,4), Q20 NUMBER(15,4),
    Q21 NUMBER(15,4), Q22 NUMBER(15,4), Q23 NUMBER(15,4), Q24 NUMBER(15,4), Q25 NUMBER(15,4),
    Q26 NUMBER(15,4), Q27 NUMBER(15,4), Q28 NUMBER(15,4), Q29 NUMBER(15,4), Q30 NUMBER(15,4),
    Q31 NUMBER(15,4), Q32 NUMBER(15,4), Q33 NUMBER(15,4), Q34 NUMBER(15,4), Q35 NUMBER(15,4),
    Q36 NUMBER(15,4), Q37 NUMBER(15,4), Q38 NUMBER(15,4), Q39 NUMBER(15,4), Q40 NUMBER(15,4),
    Q41 NUMBER(15,4), Q42 NUMBER(15,4), Q43 NUMBER(15,4), Q44 NUMBER(15,4), Q45 NUMBER(15,4),
    Q46 NUMBER(15,4), Q47 NUMBER(15,4), Q48 NUMBER(15,4), Q49 NUMBER(15,4), Q50 NUMBER(15,4),
    Q51 NUMBER(15,4), Q52 NUMBER(15,4), Q53 NUMBER(15,4), Q54 NUMBER(15,4), Q55 NUMBER(15,4),
    Q56 NUMBER(15,4), Q57 NUMBER(15,4), Q58 NUMBER(15,4), Q59 NUMBER(15,4), Q60 NUMBER(15,4),
    Q61 NUMBER(15,4), Q62 NUMBER(15,4), Q63 NUMBER(15,4), Q64 NUMBER(15,4), Q65 NUMBER(15,4),
    Q66 NUMBER(15,4), Q67 NUMBER(15,4), Q68 NUMBER(15,4), Q69 NUMBER(15,4), Q70 NUMBER(15,4),
    Q71 NUMBER(15,4), Q72 NUMBER(15,4), Q73 NUMBER(15,4), Q74 NUMBER(15,4), Q75 NUMBER(15,4),
    Q76 NUMBER(15,4), Q77 NUMBER(15,4), Q78 NUMBER(15,4), Q79 NUMBER(15,4), Q80 NUMBER(15,4),
    Q81 NUMBER(15,4), Q82 NUMBER(15,4), Q83 NUMBER(15,4), Q84 NUMBER(15,4), Q85 NUMBER(15,4),
    Q86 NUMBER(15,4), Q87 NUMBER(15,4), Q88 NUMBER(15,4), Q89 NUMBER(15,4), Q90 NUMBER(15,4),
    Q91 NUMBER(15,4), Q92 NUMBER(15,4), Q93 NUMBER(15,4), Q94 NUMBER(15,4), Q95 NUMBER(15,4),
    Q96 NUMBER(15,4), Q97 NUMBER(15,4), Q98 NUMBER(15,4), Q99 NUMBER(15,4), Q100 NUMBER(15,4),
    -- S1-S100: Status codes for each interval
    S1 VARCHAR2(5), S2 VARCHAR2(5), S3 VARCHAR2(5), S4 VARCHAR2(5), S5 VARCHAR2(5),
    S6 VARCHAR2(5), S7 VARCHAR2(5), S8 VARCHAR2(5), S9 VARCHAR2(5), S10 VARCHAR2(5),
    S11 VARCHAR2(5), S12 VARCHAR2(5), S13 VARCHAR2(5), S14 VARCHAR2(5), S15 VARCHAR2(5),
    S16 VARCHAR2(5), S17 VARCHAR2(5), S18 VARCHAR2(5), S19 VARCHAR2(5), S20 VARCHAR2(5),
    S21 VARCHAR2(5), S22 VARCHAR2(5), S23 VARCHAR2(5), S24 VARCHAR2(5), S25 VARCHAR2(5),
    S26 VARCHAR2(5), S27 VARCHAR2(5), S28 VARCHAR2(5), S29 VARCHAR2(5), S30 VARCHAR2(5),
    S31 VARCHAR2(5), S32 VARCHAR2(5), S33 VARCHAR2(5), S34 VARCHAR2(5), S35 VARCHAR2(5),
    S36 VARCHAR2(5), S37 VARCHAR2(5), S38 VARCHAR2(5), S39 VARCHAR2(5), S40 VARCHAR2(5),
    S41 VARCHAR2(5), S42 VARCHAR2(5), S43 VARCHAR2(5), S44 VARCHAR2(5), S45 VARCHAR2(5),
    S46 VARCHAR2(5), S47 VARCHAR2(5), S48 VARCHAR2(5), S49 VARCHAR2(5), S50 VARCHAR2(5),
    S51 VARCHAR2(5), S52 VARCHAR2(5), S53 VARCHAR2(5), S54 VARCHAR2(5), S55 VARCHAR2(5),
    S56 VARCHAR2(5), S57 VARCHAR2(5), S58 VARCHAR2(5), S59 VARCHAR2(5), S60 VARCHAR2(5),
    S61 VARCHAR2(5), S62 VARCHAR2(5), S63 VARCHAR2(5), S64 VARCHAR2(5), S65 VARCHAR2(5),
    S66 VARCHAR2(5), S67 VARCHAR2(5), S68 VARCHAR2(5), S69 VARCHAR2(5), S70 VARCHAR2(5),
    S71 VARCHAR2(5), S72 VARCHAR2(5), S73 VARCHAR2(5), S74 VARCHAR2(5), S75 VARCHAR2(5),
    S76 VARCHAR2(5), S77 VARCHAR2(5), S78 VARCHAR2(5), S79 VARCHAR2(5), S80 VARCHAR2(5),
    S81 VARCHAR2(5), S82 VARCHAR2(5), S83 VARCHAR2(5), S84 VARCHAR2(5), S85 VARCHAR2(5),
    S86 VARCHAR2(5), S87 VARCHAR2(5), S88 VARCHAR2(5), S89 VARCHAR2(5), S90 VARCHAR2(5),
    S91 VARCHAR2(5), S92 VARCHAR2(5), S93 VARCHAR2(5), S94 VARCHAR2(5), S95 VARCHAR2(5),
    S96 VARCHAR2(5), S97 VARCHAR2(5), S98 VARCHAR2(5), S99 VARCHAR2(5), S100 VARCHAR2(5),
    CONSTRAINT FK_CURVES_HD FOREIGN KEY (HD_LOG_ID) REFERENCES SMC_MDM_SCCURVES_HD(LOG_ID)
);

-- Indexes for SMC_MDM_SCCURVES
CREATE INDEX IDX_CURVES_HD_LOG_ID ON SMC_MDM_SCCURVES(HD_LOG_ID);
CREATE INDEX IDX_CURVES_POD_DATE ON SMC_MDM_SCCURVES(POD_ID, DATE_READ);
CREATE INDEX IDX_CURVES_SUPPLY_NUM ON SMC_MDM_SCCURVES(SUPPLY_NUM);
CREATE INDEX IDX_CURVES_DATE_READ ON SMC_MDM_SCCURVES(DATE_READ);
CREATE INDEX IDX_CURVES_SECTION_UUID ON SMC_MDM_SCCURVES(SECTION_UUID);
CREATE INDEX IDX_CURVES_SOURCE_SYSTEM ON SMC_MDM_SCCURVES(SOURCE_SYSTEM);

COMMENT ON TABLE SMC_MDM_SCCURVES IS 'Curve data with horizontal pivot (Q1-Q100 values, S1-S100 statuses)';
COMMENT ON COLUMN SMC_MDM_SCCURVES.HD_LOG_ID IS 'Foreign key to header table';
COMMENT ON COLUMN SMC_MDM_SCCURVES.SECTION_UUID IS 'Section/Channel UUID from XML for tracking';
COMMENT ON COLUMN SMC_MDM_SCCURVES.POD_ID IS 'Point of Delivery - full 22 character ID';
COMMENT ON COLUMN SMC_MDM_SCCURVES.SUPPLY_NUM IS 'Supply number - 9 chars extracted from POD_ID positions 4-12';

-- ============================================================================
-- ITRON FILE PROCESSING TABLES
-- ============================================================================

-- ITRON File Process Tracking
CREATE TABLE ITRON_FILE_PROCESS (
    F_ID                NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    F_NAME              VARCHAR2(500) NOT NULL,
    PROCESS_RESULT      NUMBER(5),
    PROCESS_MESSAGE     VARCHAR2(4000),
    DT_CREATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    DT_UPDATE           TIMESTAMP
);

CREATE INDEX IDX_ITRON_PROCESS_NAME ON ITRON_FILE_PROCESS(F_NAME);

-- ITRON Readings Data
CREATE TABLE ITRON_FILE_READINGS (
    R_ID                NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    F_ID                NUMBER(19) NOT NULL,
    SERV_POINT_CHANNEL  VARCHAR2(100),
    METER_VALUE         NUMBER(15,4),
    STATUS_REF          VARCHAR2(20),
    READING_TIME        VARCHAR2(50),
    DT_CREATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_READINGS_PROCESS FOREIGN KEY (F_ID) REFERENCES ITRON_FILE_PROCESS(F_ID)
);

CREATE INDEX IDX_ITRON_READINGS_FID ON ITRON_FILE_READINGS(F_ID);
CREATE INDEX IDX_ITRON_READINGS_CHANNEL ON ITRON_FILE_READINGS(SERV_POINT_CHANNEL);

-- ITRON Alarms Data
CREATE TABLE ITRON_FILE_ALARMS (
    A_ID                NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    F_ID                NUMBER(19) NOT NULL,
    COLLECTION_SYSTEM_ID VARCHAR2(100),
    OBJECT_ID           VARCHAR2(100),
    OBJECT_TYPE         VARCHAR2(100),
    EVENT_TYPE          VARCHAR2(100),
    EVENT_DTIME         VARCHAR2(50),
    CAPTURE_DTIME       VARCHAR2(50),
    IS_HISTORICAL       VARCHAR2(10),
    DT_CREATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_ALARMS_PROCESS FOREIGN KEY (F_ID) REFERENCES ITRON_FILE_PROCESS(F_ID)
);

CREATE INDEX IDX_ITRON_ALARMS_FID ON ITRON_FILE_ALARMS(F_ID);
CREATE INDEX IDX_ITRON_ALARMS_OBJID ON ITRON_FILE_ALARMS(OBJECT_ID);

-- ITRON Events Data
CREATE TABLE ITRON_FILE_EVENTS (
    E_ID                NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    F_ID                NUMBER(19) NOT NULL,
    COLLECTION_SYSTEM_ID VARCHAR2(100),
    OBJECT_ID           VARCHAR2(100),
    OBJECT_TYPE         VARCHAR2(100),
    EVENT_TYPE          VARCHAR2(100),
    EVENT_DTIME         VARCHAR2(50),
    CAPTURE_DTIME       VARCHAR2(50),
    DT_CREATE           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_EVENTS_PROCESS FOREIGN KEY (F_ID) REFERENCES ITRON_FILE_PROCESS(F_ID)
);

CREATE INDEX IDX_ITRON_EVENTS_FID ON ITRON_FILE_EVENTS(F_ID);
CREATE INDEX IDX_ITRON_EVENTS_OBJID ON ITRON_FILE_EVENTS(OBJECT_ID);

-- ============================================================================
-- AUDIT TABLE
-- ============================================================================

CREATE TABLE SMC_LOAD_PROFILE_AUDIT (
    AUDIT_ID            NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TABLE_NAME          VARCHAR2(50) NOT NULL,
    OPERATION           VARCHAR2(10) NOT NULL,
    RECORD_ID           NUMBER(19),
    OLD_STATUS          VARCHAR2(20),
    NEW_STATUS          VARCHAR2(20),
    CHANGED_BY          VARCHAR2(100) DEFAULT USER,
    CHANGED_AT          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    DETAILS             VARCHAR2(4000)
);

CREATE INDEX IDX_AUDIT_TABLE ON SMC_LOAD_PROFILE_AUDIT(TABLE_NAME, RECORD_ID);
CREATE INDEX IDX_AUDIT_CHANGED_AT ON SMC_LOAD_PROFILE_AUDIT(CHANGED_AT);

-- ============================================================================
-- TRIGGERS
-- ============================================================================

-- Audit trigger for header status changes
CREATE OR REPLACE TRIGGER TRG_HD_STATUS_AUDIT
AFTER UPDATE OF STATUS ON SMC_MDM_SCCURVES_HD
FOR EACH ROW
WHEN (OLD.STATUS != NEW.STATUS)
BEGIN
    INSERT INTO SMC_LOAD_PROFILE_AUDIT (
        TABLE_NAME, OPERATION, RECORD_ID, 
        OLD_STATUS, NEW_STATUS, DETAILS
    ) VALUES (
        'SMC_MDM_SCCURVES_HD', 'UPDATE', :NEW.LOG_ID,
        :OLD.STATUS, :NEW.STATUS,
        'Status changed from ' || :OLD.STATUS || ' to ' || :NEW.STATUS
    );
END;
/

-- Update DT_UPDATE on header changes
CREATE OR REPLACE TRIGGER TRG_HD_UPDATE_DT
BEFORE UPDATE ON SMC_MDM_SCCURVES_HD
FOR EACH ROW
BEGIN
    :NEW.DT_UPDATE := SYSTIMESTAMP;
END;
/

-- ============================================================================
-- VIEWS FOR ARTEMIS CONSUMPTION
-- ============================================================================

-- View: Daily summary per POD
CREATE OR REPLACE VIEW V_CURVES_DAILY_SUMMARY AS
SELECT 
    c.POD_ID,
    c.SUPPLY_NUM,
    c.DATE_READ,
    c.DATA_CLASS,
    c.SOURCE_SYSTEM,
    h.STATUS AS HEADER_STATUS,
    h.RECEIVED_AT,
    -- Sum of all Q values
    NVL(c.Q1,0)+NVL(c.Q2,0)+NVL(c.Q3,0)+NVL(c.Q4,0)+NVL(c.Q5,0)+
    NVL(c.Q6,0)+NVL(c.Q7,0)+NVL(c.Q8,0)+NVL(c.Q9,0)+NVL(c.Q10,0)+
    NVL(c.Q11,0)+NVL(c.Q12,0)+NVL(c.Q13,0)+NVL(c.Q14,0)+NVL(c.Q15,0)+
    NVL(c.Q16,0)+NVL(c.Q17,0)+NVL(c.Q18,0)+NVL(c.Q19,0)+NVL(c.Q20,0)+
    NVL(c.Q21,0)+NVL(c.Q22,0)+NVL(c.Q23,0)+NVL(c.Q24,0)+NVL(c.Q25,0)+
    NVL(c.Q26,0)+NVL(c.Q27,0)+NVL(c.Q28,0)+NVL(c.Q29,0)+NVL(c.Q30,0)+
    NVL(c.Q31,0)+NVL(c.Q32,0)+NVL(c.Q33,0)+NVL(c.Q34,0)+NVL(c.Q35,0)+
    NVL(c.Q36,0)+NVL(c.Q37,0)+NVL(c.Q38,0)+NVL(c.Q39,0)+NVL(c.Q40,0)+
    NVL(c.Q41,0)+NVL(c.Q42,0)+NVL(c.Q43,0)+NVL(c.Q44,0)+NVL(c.Q45,0)+
    NVL(c.Q46,0)+NVL(c.Q47,0)+NVL(c.Q48,0)+NVL(c.Q49,0)+NVL(c.Q50,0)+
    NVL(c.Q51,0)+NVL(c.Q52,0)+NVL(c.Q53,0)+NVL(c.Q54,0)+NVL(c.Q55,0)+
    NVL(c.Q56,0)+NVL(c.Q57,0)+NVL(c.Q58,0)+NVL(c.Q59,0)+NVL(c.Q60,0)+
    NVL(c.Q61,0)+NVL(c.Q62,0)+NVL(c.Q63,0)+NVL(c.Q64,0)+NVL(c.Q65,0)+
    NVL(c.Q66,0)+NVL(c.Q67,0)+NVL(c.Q68,0)+NVL(c.Q69,0)+NVL(c.Q70,0)+
    NVL(c.Q71,0)+NVL(c.Q72,0)+NVL(c.Q73,0)+NVL(c.Q74,0)+NVL(c.Q75,0)+
    NVL(c.Q76,0)+NVL(c.Q77,0)+NVL(c.Q78,0)+NVL(c.Q79,0)+NVL(c.Q80,0)+
    NVL(c.Q81,0)+NVL(c.Q82,0)+NVL(c.Q83,0)+NVL(c.Q84,0)+NVL(c.Q85,0)+
    NVL(c.Q86,0)+NVL(c.Q87,0)+NVL(c.Q88,0)+NVL(c.Q89,0)+NVL(c.Q90,0)+
    NVL(c.Q91,0)+NVL(c.Q92,0)+NVL(c.Q93,0)+NVL(c.Q94,0)+NVL(c.Q95,0)+
    NVL(c.Q96,0) AS DAILY_TOTAL
FROM SMC_MDM_SCCURVES c
JOIN SMC_MDM_SCCURVES_HD h ON c.HD_LOG_ID = h.LOG_ID
WHERE h.STATUS = 'SUCCESS';

-- View: Processing statistics
CREATE OR REPLACE VIEW V_PROCESSING_STATS AS
SELECT 
    TRUNC(RECEIVED_AT) AS PROCESS_DATE,
    SOURCE_SYSTEM,
    SOURCE_TYPE,
    STATUS,
    COUNT(*) AS MESSAGE_COUNT,
    SUM(RECORDS_PROCESSED) AS TOTAL_RECORDS,
    MIN(RECEIVED_AT) AS FIRST_RECEIVED,
    MAX(RECEIVED_AT) AS LAST_RECEIVED
FROM SMC_MDM_SCCURVES_HD
GROUP BY TRUNC(RECEIVED_AT), SOURCE_SYSTEM, SOURCE_TYPE, STATUS
ORDER BY PROCESS_DATE DESC, SOURCE_SYSTEM, SOURCE_TYPE;

-- ============================================================================
-- GRANTS (adjust schema/user as needed)
-- ============================================================================

-- GRANT SELECT, INSERT, UPDATE ON SMC_MDM_SCCURVES_HD TO ARTEMIS_APP;
-- GRANT SELECT, INSERT, UPDATE ON SMC_MDM_SCCURVES TO ARTEMIS_APP;
-- GRANT SELECT ON V_CURVES_DAILY_SUMMARY TO ARTEMIS_APP;
-- GRANT SELECT ON V_PROCESSING_STATS TO ARTEMIS_APP;

-- ============================================================================
-- END OF DDL
-- ============================================================================
