-- ============================================================================
-- MDM Push Integration v3.0 - Database Schema
-- 
-- Architect's Design:
-- - SMC_MDM_SCCURVES_HD: Master/Header table (not just debug)
-- - SMC_MDM_SCCURVES: Curve data with HD_LOG_ID FK
-- - SMC_MDM_OBIS_CODES: Reference table for OBIS codes
--
-- Key Changes from v2:
-- - Renamed: SMC_MDM_DEBUG_LOG → SMC_MDM_SCCURVES_HD
-- - Renamed FK: DEBUG_LOG_ID → HD_LOG_ID  
-- - Renamed: ERROR_MSG → STATUS_MSG
-- - Added: SOURCE_SYSTEM, SOURCE_TYPE for multi-source support
-- - Added: FILE_ID, FILE_NAME for ITRON
-- - Added: SECTION_UUID for inner XML UUID tracking
-- - Added: DT_CREATE, DT_UPDATE to curves table
-- ============================================================================

-- Drop existing objects (if needed)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SMC_MDM_SCCURVES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SMC_MDM_SCCURVES_HD CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SMC_MDM_OBIS_CODES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- ============================================================================
-- Table 1: SMC_MDM_SCCURVES_HD (Header/Master Table)
-- ============================================================================

CREATE TABLE SMC_MDM_SCCURVES_HD (
    -- Primary Key
    LOG_ID              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
                        MINVALUE 1 MAXVALUE 9999999999999999999999999999 
                        INCREMENT BY 1 START WITH 1 CACHE 20 
                        NOT NULL ENABLE,
    
    -- Source Classification (per Architect's request)
    SOURCE_SYSTEM       VARCHAR2(20) NOT NULL ENABLE,       -- {ZFA, ITRON}
    SOURCE_TYPE         VARCHAR2(20) NOT NULL ENABLE,       -- {MEASURE, ALARM, EVENT}
    
    -- File Identification (for ITRON)
    FILE_ID             VARCHAR2(100),                      -- ITRON file identifier
    FILE_NAME           VARCHAR2(255),                      -- ITRON SFTP filename
    
    -- Message Identification
    MESSAGE_UUID        VARCHAR2(64),                       -- From XML bulk-level <UUID>
    WSDL_OPERATION      VARCHAR2(100),                      -- WSDL operation name
    ENDPOINT            VARCHAR2(200),                      -- REST endpoint URL
    
    -- Sender/Recipient
    SENDER_ID           VARCHAR2(50),                       -- From XML <SenderParty><StandardID>
    RECIPIENT_ID        VARCHAR2(50),                       -- From XML <RecipientParty><StandardID>
    
    -- Timestamps
    SOURCE_CREATION_DT  TIMESTAMP(6),                       -- From XML <CreationDateTime>
    RECEIVED_AT         TIMESTAMP(6) DEFAULT SYSTIMESTAMP,  -- Our receive time
    
    -- Processing Status
    STATUS              VARCHAR2(20) DEFAULT 'PENDING',     -- PENDING, SUCCESS, PARTIAL, ERROR
    STATUS_MSG          VARCHAR2(4000),                     -- Empty unless error (κενό εκτός αν πάει κάτι στραβά)
    RECORDS_PROCESSED   NUMBER(10) DEFAULT 0,               -- Count of curve records created
    
    -- Raw Payload
    RAW_XML             CLOB,                               -- Full source XML for replay/debug
    
    -- System Timestamps
    DT_CREATE           TIMESTAMP(6) DEFAULT SYSTIMESTAMP,  -- Record creation time
    DT_UPDATE           TIMESTAMP(6) DEFAULT SYSTIMESTAMP,  -- Last update time
    
    -- Constraints
    CONSTRAINT PK_SMC_MDM_SCCURVES_HD PRIMARY KEY (LOG_ID),
    CONSTRAINT CK_HD_SOURCE_SYSTEM CHECK (SOURCE_SYSTEM IN ('ZFA', 'ITRON')),
    CONSTRAINT CK_HD_SOURCE_TYPE CHECK (SOURCE_TYPE IN ('MEASURE', 'ALARM', 'EVENT'))
);

-- Indexes for SMC_MDM_SCCURVES_HD
CREATE INDEX IDX_HD_UUID ON SMC_MDM_SCCURVES_HD (MESSAGE_UUID);
CREATE INDEX IDX_HD_STATUS ON SMC_MDM_SCCURVES_HD (STATUS, RECEIVED_AT);
CREATE INDEX IDX_HD_SOURCE ON SMC_MDM_SCCURVES_HD (SOURCE_SYSTEM, SOURCE_TYPE);
CREATE INDEX IDX_HD_FILE ON SMC_MDM_SCCURVES_HD (FILE_ID);
CREATE INDEX IDX_HD_SOURCE_DT ON SMC_MDM_SCCURVES_HD (SOURCE_CREATION_DT);

-- Comments
COMMENT ON TABLE SMC_MDM_SCCURVES_HD IS 'Header/Master table for MDM curve data - contains audit trail AND master information';
COMMENT ON COLUMN SMC_MDM_SCCURVES_HD.SOURCE_SYSTEM IS 'Source system: ZFA or ITRON';
COMMENT ON COLUMN SMC_MDM_SCCURVES_HD.SOURCE_TYPE IS 'Record type: MEASURE, ALARM, EVENT (mainly for ITRON)';
COMMENT ON COLUMN SMC_MDM_SCCURVES_HD.FILE_ID IS 'File identifier for ITRON source';
COMMENT ON COLUMN SMC_MDM_SCCURVES_HD.MESSAGE_UUID IS 'Bulk-level UUID from XML MessageHeader';
COMMENT ON COLUMN SMC_MDM_SCCURVES_HD.SOURCE_CREATION_DT IS 'CreationDateTime from XML - source system timestamp';
COMMENT ON COLUMN SMC_MDM_SCCURVES_HD.RECEIVED_AT IS 'Timestamp when OUR system received the message';
COMMENT ON COLUMN SMC_MDM_SCCURVES_HD.STATUS_MSG IS 'Status message - empty unless error (renamed from ERROR_MSG)';

-- ============================================================================
-- Table 2: SMC_MDM_SCCURVES (Curve Data Table)
-- ============================================================================

CREATE TABLE SMC_MDM_SCCURVES (
    -- Primary Key
    ID                  NUMBER GENERATED ALWAYS AS IDENTITY 
                        MINVALUE 1 MAXVALUE 9999999999999999999999999999 
                        INCREMENT BY 1 START WITH 1 CACHE 20 
                        NOT NULL ENABLE,
    
    -- Foreign Key to Header (renamed per Architect's request)
    HD_LOG_ID           NUMBER NOT NULL ENABLE,
    
    -- Section UUID (from inner XML <UUID> per channel)
    SECTION_UUID        VARCHAR2(64),                       -- From inner MessageHeader <UUID>
    
    -- Meter Identification
    POD_ID              VARCHAR2(22) NOT NULL ENABLE,       -- Full 22-char UtilitiesPointOfDeliveryPartyID
    SUPPLY_NUM          CHAR(9) NOT NULL ENABLE,            -- Extracted: SUBSTR(POD_ID, 4, 9)
    METER_NO            VARCHAR2(50),                       -- Nullable - NOT in ZFA XML
    
    -- Data Classification
    DATE_READ           DATE NOT NULL ENABLE,               -- Calendar date (Greek local time)
    DATA_CLASS          VARCHAR2(30) NOT NULL ENABLE,       -- OBIS code: '1-11:1.5.0', etc.
    UNIT_MEASURE        VARCHAR2(10),                       -- From XML unitCode: 'KWH'
    
    -- Source Tracking (for connecting related records)
    SOURCE_SYSTEM       VARCHAR2(20),                       -- 'ZFA', 'ITRON'
    SOURCE_CREATION_DT  TIMESTAMP(6),                       -- From XML <CreationDateTime>
    
    -- Processing Status (for downstream ARTEMIS)
    PROCESS_FLG         NUMBER(1,0) DEFAULT 0,              -- 0=unprocessed, 1=processed
    PROCESS_DATE        DATE,                               -- When processed by downstream
    
    -- System Timestamps (per Architect's request)
    DT_CREATE           TIMESTAMP(6) DEFAULT SYSTIMESTAMP,  -- Record creation time
    DT_UPDATE           TIMESTAMP(6) DEFAULT SYSTIMESTAMP,  -- Last update time
    
    -- ========================================================================
    -- Quantity Values: Q1-Q96 (96 x 15-min intervals = 24 hours)
    -- Q1 = 00:00-00:14, Q2 = 00:15-00:29, ... Q96 = 23:45-23:59
    -- Q97-Q100 kept for backward compatibility
    -- ========================================================================
    Q1 NUMBER(14,3), Q2 NUMBER(14,3), Q3 NUMBER(14,3), Q4 NUMBER(14,3), Q5 NUMBER(14,3),
    Q6 NUMBER(14,3), Q7 NUMBER(14,3), Q8 NUMBER(14,3), Q9 NUMBER(14,3), Q10 NUMBER(14,3),
    Q11 NUMBER(14,3), Q12 NUMBER(14,3), Q13 NUMBER(14,3), Q14 NUMBER(14,3), Q15 NUMBER(14,3),
    Q16 NUMBER(14,3), Q17 NUMBER(14,3), Q18 NUMBER(14,3), Q19 NUMBER(14,3), Q20 NUMBER(14,3),
    Q21 NUMBER(14,3), Q22 NUMBER(14,3), Q23 NUMBER(14,3), Q24 NUMBER(14,3), Q25 NUMBER(14,3),
    Q26 NUMBER(14,3), Q27 NUMBER(14,3), Q28 NUMBER(14,3), Q29 NUMBER(14,3), Q30 NUMBER(14,3),
    Q31 NUMBER(14,3), Q32 NUMBER(14,3), Q33 NUMBER(14,3), Q34 NUMBER(14,3), Q35 NUMBER(14,3),
    Q36 NUMBER(14,3), Q37 NUMBER(14,3), Q38 NUMBER(14,3), Q39 NUMBER(14,3), Q40 NUMBER(14,3),
    Q41 NUMBER(14,3), Q42 NUMBER(14,3), Q43 NUMBER(14,3), Q44 NUMBER(14,3), Q45 NUMBER(14,3),
    Q46 NUMBER(14,3), Q47 NUMBER(14,3), Q48 NUMBER(14,3), Q49 NUMBER(14,3), Q50 NUMBER(14,3),
    Q51 NUMBER(14,3), Q52 NUMBER(14,3), Q53 NUMBER(14,3), Q54 NUMBER(14,3), Q55 NUMBER(14,3),
    Q56 NUMBER(14,3), Q57 NUMBER(14,3), Q58 NUMBER(14,3), Q59 NUMBER(14,3), Q60 NUMBER(14,3),
    Q61 NUMBER(14,3), Q62 NUMBER(14,3), Q63 NUMBER(14,3), Q64 NUMBER(14,3), Q65 NUMBER(14,3),
    Q66 NUMBER(14,3), Q67 NUMBER(14,3), Q68 NUMBER(14,3), Q69 NUMBER(14,3), Q70 NUMBER(14,3),
    Q71 NUMBER(14,3), Q72 NUMBER(14,3), Q73 NUMBER(14,3), Q74 NUMBER(14,3), Q75 NUMBER(14,3),
    Q76 NUMBER(14,3), Q77 NUMBER(14,3), Q78 NUMBER(14,3), Q79 NUMBER(14,3), Q80 NUMBER(14,3),
    Q81 NUMBER(14,3), Q82 NUMBER(14,3), Q83 NUMBER(14,3), Q84 NUMBER(14,3), Q85 NUMBER(14,3),
    Q86 NUMBER(14,3), Q87 NUMBER(14,3), Q88 NUMBER(14,3), Q89 NUMBER(14,3), Q90 NUMBER(14,3),
    Q91 NUMBER(14,3), Q92 NUMBER(14,3), Q93 NUMBER(14,3), Q94 NUMBER(14,3), Q95 NUMBER(14,3),
    Q96 NUMBER(14,3), Q97 NUMBER(14,3), Q98 NUMBER(14,3), Q99 NUMBER(14,3), Q100 NUMBER(14,3),

    -- ========================================================================
    -- Status Values: S1-S96 (status code per 15-min interval)
    -- Values: 'C' = Confirmed, 'E' = Estimated, 'EC' = Estimated-Confirmed
    -- ========================================================================
    S1 VARCHAR2(20), S2 VARCHAR2(20), S3 VARCHAR2(20), S4 VARCHAR2(20), S5 VARCHAR2(20),
    S6 VARCHAR2(20), S7 VARCHAR2(20), S8 VARCHAR2(20), S9 VARCHAR2(20), S10 VARCHAR2(20),
    S11 VARCHAR2(20), S12 VARCHAR2(20), S13 VARCHAR2(20), S14 VARCHAR2(20), S15 VARCHAR2(20),
    S16 VARCHAR2(20), S17 VARCHAR2(20), S18 VARCHAR2(20), S19 VARCHAR2(20), S20 VARCHAR2(20),
    S21 VARCHAR2(20), S22 VARCHAR2(20), S23 VARCHAR2(20), S24 VARCHAR2(20), S25 VARCHAR2(20),
    S26 VARCHAR2(20), S27 VARCHAR2(20), S28 VARCHAR2(20), S29 VARCHAR2(20), S30 VARCHAR2(20),
    S31 VARCHAR2(20), S32 VARCHAR2(20), S33 VARCHAR2(20), S34 VARCHAR2(20), S35 VARCHAR2(20),
    S36 VARCHAR2(20), S37 VARCHAR2(20), S38 VARCHAR2(20), S39 VARCHAR2(20), S40 VARCHAR2(20),
    S41 VARCHAR2(20), S42 VARCHAR2(20), S43 VARCHAR2(20), S44 VARCHAR2(20), S45 VARCHAR2(20),
    S46 VARCHAR2(20), S47 VARCHAR2(20), S48 VARCHAR2(20), S49 VARCHAR2(20), S50 VARCHAR2(20),
    S51 VARCHAR2(20), S52 VARCHAR2(20), S53 VARCHAR2(20), S54 VARCHAR2(20), S55 VARCHAR2(20),
    S56 VARCHAR2(20), S57 VARCHAR2(20), S58 VARCHAR2(20), S59 VARCHAR2(20), S60 VARCHAR2(20),
    S61 VARCHAR2(20), S62 VARCHAR2(20), S63 VARCHAR2(20), S64 VARCHAR2(20), S65 VARCHAR2(20),
    S66 VARCHAR2(20), S67 VARCHAR2(20), S68 VARCHAR2(20), S69 VARCHAR2(20), S70 VARCHAR2(20),
    S71 VARCHAR2(20), S72 VARCHAR2(20), S73 VARCHAR2(20), S74 VARCHAR2(20), S75 VARCHAR2(20),
    S76 VARCHAR2(20), S77 VARCHAR2(20), S78 VARCHAR2(20), S79 VARCHAR2(20), S80 VARCHAR2(20),
    S81 VARCHAR2(20), S82 VARCHAR2(20), S83 VARCHAR2(20), S84 VARCHAR2(20), S85 VARCHAR2(20),
    S86 VARCHAR2(20), S87 VARCHAR2(20), S88 VARCHAR2(20), S89 VARCHAR2(20), S90 VARCHAR2(20),
    S91 VARCHAR2(20), S92 VARCHAR2(20), S93 VARCHAR2(20), S94 VARCHAR2(20), S95 VARCHAR2(20),
    S96 VARCHAR2(20), S97 VARCHAR2(20), S98 VARCHAR2(20), S99 VARCHAR2(20), S100 VARCHAR2(20),

    -- Constraints
    CONSTRAINT PK_SMC_MDM_SCCURVES PRIMARY KEY (ID),
    CONSTRAINT FK_SCCURVES_HD FOREIGN KEY (HD_LOG_ID)
        REFERENCES SMC_MDM_SCCURVES_HD (LOG_ID) ENABLE
    -- NOTE: No unique constraint - duplicates allowed, downstream system unifies
);

-- Indexes for SMC_MDM_SCCURVES
CREATE INDEX IDX_SCCURVES_HD ON SMC_MDM_SCCURVES (HD_LOG_ID);
CREATE INDEX IDX_SCCURVES_SECTION ON SMC_MDM_SCCURVES (SECTION_UUID);
CREATE INDEX IDX_SCCURVES_POD_DATE ON SMC_MDM_SCCURVES (POD_ID, DATE_READ, DATA_CLASS);
CREATE INDEX IDX_SCCURVES_SUPPLY ON SMC_MDM_SCCURVES (SUPPLY_NUM, DATE_READ);
CREATE INDEX IDX_SCCURVES_PROCESS ON SMC_MDM_SCCURVES (PROCESS_FLG, DATE_READ);
CREATE INDEX IDX_SCCURVES_SOURCE_DT ON SMC_MDM_SCCURVES (SOURCE_CREATION_DT);

-- Comments
COMMENT ON TABLE SMC_MDM_SCCURVES IS 'Curve data - one row per POD+Channel+Date with 96 interval values';
COMMENT ON COLUMN SMC_MDM_SCCURVES.HD_LOG_ID IS 'FK to header table SMC_MDM_SCCURVES_HD (renamed from DEBUG_LOG_ID)';
COMMENT ON COLUMN SMC_MDM_SCCURVES.SECTION_UUID IS 'Inner message UUID from XML (per channel/profile)';
COMMENT ON COLUMN SMC_MDM_SCCURVES.POD_ID IS 'Full 22-char Point of Delivery ID from XML';
COMMENT ON COLUMN SMC_MDM_SCCURVES.SUPPLY_NUM IS '9-char supply number: SUBSTR(POD_ID, 4, 9)';
COMMENT ON COLUMN SMC_MDM_SCCURVES.DATE_READ IS 'Calendar date (converted from UTC to Greek local time)';
COMMENT ON COLUMN SMC_MDM_SCCURVES.DATA_CLASS IS 'OBIS code: 1-11:1.5.0=Active+, 1-12:2.5.0=Active-';
COMMENT ON COLUMN SMC_MDM_SCCURVES.SOURCE_CREATION_DT IS 'XML CreationDateTime - for correlating related records';
COMMENT ON COLUMN SMC_MDM_SCCURVES.PROCESS_FLG IS 'Processing flag for downstream ARTEMIS: 0=unprocessed, 1=processed';
COMMENT ON COLUMN SMC_MDM_SCCURVES.PROCESS_DATE IS 'Date when processed by downstream ARTEMIS system';

-- ============================================================================
-- Table 3: SMC_MDM_OBIS_CODES (Reference Table)
-- ============================================================================

CREATE TABLE SMC_MDM_OBIS_CODES (
    OBIS_CODE           VARCHAR2(30) NOT NULL,
    CHANNEL_NAME        VARCHAR2(50) NOT NULL,
    CHANNEL_TYPE        VARCHAR2(20) NOT NULL,              -- ACTIVE, REACTIVE
    DIRECTION           VARCHAR2(10),                       -- IN (consumed), OUT (produced)
    DESCRIPTION         VARCHAR2(200),
    IS_ACTIVE           CHAR(1) DEFAULT 'Y',
    CONSTRAINT PK_SMC_MDM_OBIS_CODES PRIMARY KEY (OBIS_CODE),
    CONSTRAINT CK_OBIS_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N'))
);

-- Insert standard OBIS codes for ZFA
INSERT INTO SMC_MDM_OBIS_CODES (OBIS_CODE, CHANNEL_NAME, CHANNEL_TYPE, DIRECTION, DESCRIPTION) 
VALUES ('1-11:1.5.0', 'Active+', 'ACTIVE', 'IN', 'Active energy consumed (imported) per 15-min interval');

INSERT INTO SMC_MDM_OBIS_CODES (OBIS_CODE, CHANNEL_NAME, CHANNEL_TYPE, DIRECTION, DESCRIPTION) 
VALUES ('1-12:2.5.0', 'Active-', 'ACTIVE', 'OUT', 'Active energy produced (exported) per 15-min interval');

INSERT INTO SMC_MDM_OBIS_CODES (OBIS_CODE, CHANNEL_NAME, CHANNEL_TYPE, DIRECTION, DESCRIPTION) 
VALUES ('1-11:5.5.0', 'Reactive+/Q1', 'REACTIVE', 'IN', 'Reactive energy absorbed from network');

INSERT INTO SMC_MDM_OBIS_CODES (OBIS_CODE, CHANNEL_NAME, CHANNEL_TYPE, DIRECTION, DESCRIPTION) 
VALUES ('1-12:8.5.0', 'Reactive-/Q2', 'REACTIVE', 'OUT', 'Reactive energy given to network');

COMMIT;

-- ============================================================================
-- Verification
-- ============================================================================

SELECT table_name, COUNT(*) as column_count
FROM user_tab_columns 
WHERE table_name IN ('SMC_MDM_SCCURVES_HD', 'SMC_MDM_SCCURVES', 'SMC_MDM_OBIS_CODES')
GROUP BY table_name
ORDER BY table_name;

SELECT * FROM SMC_MDM_OBIS_CODES;

PROMPT
PROMPT =====================================================
PROMPT MDM Push v3.0 Database Schema Created Successfully!
PROMPT 
PROMPT Tables:
PROMPT   - SMC_MDM_SCCURVES_HD (Header/Master)
PROMPT   - SMC_MDM_SCCURVES (Curve Data)
PROMPT   - SMC_MDM_OBIS_CODES (Reference)
PROMPT =====================================================
PROMPT
